import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const AllPostsPage: NextPage = () => {
  const { locale, query } = useRouter();
  console.log(locale, query);
  return (
    <div>
      <Head>
        <title>All Posts - Predifast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default AllPostsPage;
